# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: develop  ci

on:
  schedule:
    - cron: '0 0 */2 * *' # This triggers the workflow daily at midnight UTC
  workflow_dispatch: # Allows the workflow to be manually triggered
    inputs:
      GitUrl:
        description: 'ckb -git url'
        default: 'https://github.com/nervosnetwork/ckb.git'
      GitBranch:
        description: 'ckb -git branch'
        default: 'develop'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Install dependencies
      run: make develop_prepare
      env:
        GitUrl: '${{ github.event.inputs.GitUrl }}'
        GitBranch: '${{ github.event.inputs.GitBranch }}'


    - name: Run tests
      run: make test


    - name: Publish reports
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: jfoa-build-reports-${{ runner.os }}
        path: ./report
