name: Lint and Format

on: [push, pull_request]

jobs:
  lint_and_format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black pylint

    - name: Run black
      run: black --check .

#    - name: Run pylint
#      run: pylint $(find . -name "*.py")

    - name: Format code
      run: |
        chmod +x format_code.sh
        ./format_code.sh
